string IDLE=idle
string CHARGING=charging
string DISCHARGING=discharging
string FULL=full
string charge_status                   #充放电状态

float32   voltage                      #电池总电压
float32   current                      #电池总电流
float32   temperature                  #电池温度
float32   maxdifvol                    #最大压差
float32   batsoc                       #电池总容量
float32   remainchargetime             #剩余充电时间
uint16    healthstatus                 #健康状态
float32   remainuselife                #电池剩余寿命(循环周期数)
