float32    adc_orin_value
float32    adc_orin_ibus_value       #Orin电流  A
float32    adc_arm_ibus_value
float32    adc_ibus_value
float32    adc_leftleg_ibus_value
float32    adc_rightleg_ibus_value
float32    adc_waist_ibus_value      #腰部电流 A
float32    adc_charge_det_value
float32    adc_vdc1_value
float32    adc_mos_temp
float32    adc_1v5
float32    temptature
float32    vrefint
float32    adc_x86_ibus_value        #x86电流    A
float32    adc_rk_ibus_value     #rk电流  A
float32    adc_3vref_value           #3v参考电压  V
uint16     err_code

uint8 second         #秒
uint8 minute         #分
uint8 hour           #时
uint8 day            #日
uint8 month          #月
uint16 year          #年

